import json, yt
sugs = yt.autocomplete("cortisol")
print("AUTOCOMPLETE:", len(sugs), sugs[:3])
vids = yt.search("cortisol belly fat", limit=5)
print("SEARCH:", len(vids))
for v in vids: print("  ", v["views"], v["title"][:50])
cid = yt.resolve_channel("@hubermanlab")
print("RESOLVE:", cid)
meta = yt.channel_meta(cid)
print("META subs:", meta["subs"])
cv = yt.channel_videos(cid, limit=5)
print("CHANNEL VIDEOS:", len(cv), [v["views"] for v in cv])
info = yt.video_info("QyPUDMKVjyk")
print("PLAYER:", info["views"], info["title"])
ok = all([sugs, vids, cid, meta["subs"], cv])
print("RESULT:", "PASS" if ok else "FAIL")
raise SystemExit(0 if ok else 1)
